name: Deployment to AliYun
# on:
#   push:
#     branches:
#       - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm and Node
        uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true
          install: false
          require-lockfile: true
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Build page
        run: pnpm build
      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1.4.1
        with:
          accessKeyId: ${{ secrets.YUN_KEY_ID }}
          accessKeySecret: ${{ secrets.YUN_KEY_SECRET }}
          bucket: 'qwerty-front'
          endpoint: 'oss-cn-beijing.aliyuncs.com'
          folder: './build'
          skipSetting: true
